version: '3.9'
services:
  postgres:
    image: postgres:17.0
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
volumes:
  postgres_data: